### ISSUE TITLE
NIT CONF Site

### ISSUE THREAD

**Issue by Rohithhh28** [Rohithhh28/SElab_P1#9]
NITCONF RMS is basic web application used by reviewers in conference.

This have the following components  :
- [x] https://github.com/Rohithhh28/SElab_P1/issues/10    1.2
- [x] https://github.com/Rohithhh28/SElab_P1/issues/11    2
- [x] https://github.com/Rohithhh28/SElab_P1/issues/12  3

**Comment by tbharath03** [comment]
Done, Close this issue
